#!/usr/bin/env sh

set -e

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=$(git hash-object -t tree /dev/null)
fi

if type shellcheck > /dev/null; then
    for i in eebydeeby ebdb-kernel git-hooks/*; do
        case "$(git status --porcelain "$i")" in
        ?M*)
            shellcheck "$i"
        esac
    done
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached "$against" --
